### ISSUE TITLE
Possibility to set flags

### ISSUE THREAD

**Issue by Kuzmin** [mquandalle/meteor-harmony#36]
I want to user traceur type assertions with this library, so it would be neat if there was a possibility to set config flags on the compiler. (--type-assertions, --annotations etc)

**Comment by Sanjo** [comment]
Wouldn't a JSON config file like /harmony.json work that you can read before transpiling the files?

**Comment by grigio** [comment]
In `grigio:babel` there is an optional `babel.json` file to configure the compiler per project https://github.com/grigio/meteor-babel/blob/master/plugin/compile-6to5.js#L49-L62
